<a href="https://colab.research.google.com/github/UlinYang/git-tutorial/blob/main/practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.rand(2,3)
matrix = np.random.rand(2,3)
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0.8088, 0.5527, 0.3844],
        [0.5957, 0.7677, 0.1717]])
Matrix:
 [[0.32705306 0.97203524 0.22973465]
 [0.3232886  0.83870425 0.19018621]]


In [3]:
tensor = torch.zeros(2,3)
matrix = np.zeros((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
tensor = torch.ones(2,3)
matrix = np.ones((2,3))
print(f"Tensor:\n {tensor}")
print(f"Matrix:\n {matrix}")

Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(f"Tensor:\n {tensor.dtype}")
print(f"Matrix:\n {matrix.dtype}")

Tensor:
 torch.float32
Matrix:
 float64


In [6]:
print(f"Tensor:\n {tensor.size()}")
print(f"Tensor:\n {tensor.shape}")
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([2, 3])
Tensor:
 torch.Size([2, 3])
Matrix:
 (2, 3)


In [7]:
# list to torch
tensor = torch.tensor([2.3, 1.2, 5.7])
print(f"Tensor:\n {tensor.size()}")

# list to numpy
matrix = np.array([2.3, 1.2, 5.7])
print(f"Matrix:\n {matrix.shape}")

Tensor:
 torch.Size([3])
Matrix:
 (3,)


In [8]:
# numpy <=> torch
tensor = torch.tensor([1, 2, 3])
matrix = np.array([1, 2, 3])
print(torch.from_numpy(matrix))
print(tensor.numpy())

tensor([1, 2, 3])
[1 2 3]


In [9]:
# call by reference
tensor = torch.tensor([1, 2, 3])
matrix = tensor.numpy()

tensor += 1
print(tensor)
print(matrix)

tensor([2, 3, 4])
[2 3 4]


In [12]:
# operator 
t1 = torch.tensor([2.3, 1.2, 5.7])
t2 = torch.tensor([3.2, 2.8, 7.8])
print(torch.add(t1, t2)) # t1 + t2
print(torch.sub(t1, t2)) # t1 - t2
print(torch.mul(t1, t2)) # t1 * t2
print(torch.div(t1, t2)) # t1 / t2

tensor([ 5.5000,  4.0000, 13.5000])
tensor([-0.9000, -1.6000, -2.1000])
tensor([ 7.3600,  3.3600, 44.4600])
tensor([0.7188, 0.4286, 0.7308])


In [13]:
# slice
tensor = torch.rand(5,3)
print(tensor)
print(tensor[:,1:3])
print(tensor[1,1].item())

tensor([[0.0654, 0.5050, 0.4955],
        [0.0336, 0.8246, 0.6069],
        [0.8794, 0.5914, 0.8932],
        [0.5411, 0.3636, 0.9116],
        [0.9381, 0.2412, 0.6803]])
tensor([[0.5050, 0.4955],
        [0.8246, 0.6069],
        [0.5914, 0.8932],
        [0.3636, 0.9116],
        [0.2412, 0.6803]])
0.8245742321014404


In [14]:
# view
tensor = torch.rand(2,6)
print(tensor)
print(tensor.view(3,4))
print(tensor.view(12))
print(tensor.view(12,1))
print(tensor.view(1,12))
print(tensor.view(-1,3))

tensor([[0.1252, 0.7135, 0.4713, 0.6988, 0.9257, 0.4870],
        [0.6097, 0.7308, 0.8275, 0.6712, 0.2861, 0.7272]])
tensor([[0.1252, 0.7135, 0.4713, 0.6988],
        [0.9257, 0.4870, 0.6097, 0.7308],
        [0.8275, 0.6712, 0.2861, 0.7272]])
tensor([0.1252, 0.7135, 0.4713, 0.6988, 0.9257, 0.4870, 0.6097, 0.7308, 0.8275,
        0.6712, 0.2861, 0.7272])
tensor([[0.1252],
        [0.7135],
        [0.4713],
        [0.6988],
        [0.9257],
        [0.4870],
        [0.6097],
        [0.7308],
        [0.8275],
        [0.6712],
        [0.2861],
        [0.7272]])
tensor([[0.1252, 0.7135, 0.4713, 0.6988, 0.9257, 0.4870, 0.6097, 0.7308, 0.8275,
         0.6712, 0.2861, 0.7272]])
tensor([[0.1252, 0.7135, 0.4713],
        [0.6988, 0.9257, 0.4870],
        [0.6097, 0.7308, 0.8275],
        [0.6712, 0.2861, 0.7272]])


In [15]:
# GPU
print(torch.cuda.is_available())
# if torch.cuda.is_available():
#   device = torch.device("cuda")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(3,2).to(device)
print(x)
x = x.to("cpu")
print(x)

True
tensor([[0.8946, 0.9282],
        [0.7663, 0.1818],
        [0.3857, 0.7407]], device='cuda:0')
tensor([[0.8946, 0.9282],
        [0.7663, 0.1818],
        [0.3857, 0.7407]])
